name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Update Version
        run: |
          cd tools
          npm install
          npx ts-node update_version.ts
          cd ..

      - name: Commit version update
        run: |
          if [[ "${{ github.event.head_commit.message }}" != *"[skip-version]"* ]]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add lib/version.dart
            git commit -m "Auto-increment version number [skip ci]" || echo "No changes to commit"
            git push
          fi
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Enable Web
        run: flutter config --enable-web
        
      - name: Get dependencies
        run: flutter pub get
        
      - name: Build web
        run: flutter build web --base-href "/explain_1/"

      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/web'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4